name: 'Hello World Docker Action'
inputs: 
  who-to-greet:
   default: 'world'
outputs:
  time:
    description: 'time of action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
