name: CI build
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow-dispatch:
  
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3.3.0
      
      - name: run own action
      - id: hello_action
      - uses: ./hello-world-docker-action
      - with:
        who-to-greet: '@lambdaBoost'
        
      -name: output_time
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
      
