name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: [./github/**]
  pull-request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "${{ github.event_name }} job triggered"
        echo "branch is ${{ github.ref }} repo is ."
        
      - uses: actions/checkout@v3.3.0
      - name: List files in repo
        run: |
          tree
      
